import { describe,expect,it } from 'vitest';
import { BODY,COURSE_ROW_ZERO_Y,LIMBS,ROUTE_SEQUENCE,STARTING_HOLD_IDS,START_TORSO_Y,createWorld,generateChunk,generateDecisionRow,gradeApproach,interactWithHold,launchTorso,maintainCourse,rowColor,stabilizeHead,stepWorld,supportCount,torsoCenter,torsoLaunchPower,tryGrip,updateCamera,updateFocus } from './world';
import { TUNING } from './tuning';

describe('four-limb climbing',()=>{
 it('starts deterministically on two distinct pink hand holds and two planted feet without link strain',()=>{const a=createWorld(),b=createWorld();expect(a).toEqual(b);expect([a.activeRoute,a.nextRoute]).toEqual(['pink','blue']);expect(a.grips).toEqual([{limb:BODY.handL,hold:STARTING_HOLD_IDS.left},{limb:BODY.handR,hold:STARTING_HOLD_IDS.right}]);expect(a.floorSupports).toEqual([BODY.footL,BODY.footR]);expect(supportCount(a)).toBe(4);expect(a.gripProtectedUntil).toEqual({});const before=a.links.map(link=>Math.hypot(a.particles[link.a].x-a.particles[link.b].x,a.particles[link.a].y-a.particles[link.b].y)-link.length);expect(Math.max(...before.map(Math.abs))).toBeCloseTo(0);for(const grip of a.grips){const hold=a.holds.find(h=>h.id===grip.hold)!;expect(hold.color).toBe('pink');expect(a.particles[grip.limb]).toMatchObject({x:hold.x,y:hold.y});}expect(a.particles[BODY.handL].x).toBeLessThan(a.particles[BODY.handR].x);stepWorld(a);for(const limb of a.floorSupports)expect(a.particles[limb].y).toBe(TUNING.groundY-a.particles[limb].radius);});
 it('authors an upright anatomical start with overhead reserved holds and a zero-height torso baseline',()=>{const w=createWorld(),p=w.particles,start=w.holds.filter(h=>h.id===STARTING_HOLD_IDS.left||h.id===STARTING_HOLD_IDS.right);expect(start.map(h=>h.id)).toEqual([STARTING_HOLD_IDS.left,STARTING_HOLD_IDS.right]);expect(p[BODY.head].y).toBeLessThan(Math.min(p[BODY.shoulderL].y,p[BODY.shoulderR].y));expect(Math.max(p[BODY.shoulderL].y,p[BODY.shoulderR].y)).toBeLessThan(Math.min(p[BODY.hipL].y,p[BODY.hipR].y));expect(Math.max(p[BODY.hipL].y,p[BODY.hipR].y)).toBeLessThan(Math.min(p[BODY.kneeL].y,p[BODY.kneeR].y));expect(Math.max(p[BODY.kneeL].y,p[BODY.kneeR].y)).toBeLessThan(Math.min(p[BODY.footL].y,p[BODY.footR].y));for(const h of start){expect(h.y).toBeLessThan(p[BODY.head].y);expect(h.y).toBeLessThan(Math.min(p[BODY.shoulderL].y,p[BODY.shoulderR].y));}expect(torsoCenter(w).y).toBe(START_TORSO_Y);expect(w.height).toBe(0);});
 it('releases either starting hand immediately and independently',()=>{for(const first of [STARTING_HOLD_IDS.left,STARTING_HOLD_IDS.right]){const w=createWorld();expect(interactWithHold(w,first,0)).toBe('released');expect(w.grips).toHaveLength(1);expect(w.floorSupports).toEqual([BODY.footL,BODY.footR]);expect(supportCount(w)).toBe(3);const remaining=w.grips[0].hold;expect(remaining).not.toBe(first);expect(interactWithHold(w,remaining,0)).toBe('released');expect(supportCount(w)).toBe(2);}});
 it('keeps the authored four-support pose finite and mechanically settled',()=>{const w=createWorld();for(let i=0;i<600;i++)stepWorld(w);expect(supportCount(w)).toBe(4);expect(w.particles.every(p=>[p.x,p.y,p.previous.x,p.previous.y].every(Number.isFinite))).toBe(true);for(const link of w.links){const actual=Math.hypot(w.particles[link.a].x-w.particles[link.b].x,w.particles[link.a].y-w.particles[link.b].y);expect(actual/link.length).toBeLessThan(1.1);}});
 it('is deterministic and pins four independent grips',()=>{const a=createWorld(),b=createWorld(),ids=[STARTING_HOLD_IDS.left,STARTING_HOLD_IDS.right,...generateDecisionRow(2).slice(0,2).map(h=>h.id)];for(const w of [a,b]){w.floorSupports=[];w.grips=LIMBS.map((limb,i)=>({limb,hold:ids[i]}));}for(let i=0;i<600;i++){stepWorld(a);stepWorld(b);}expect(a).toEqual(b);for(const g of a.grips){const h=a.holds.find(hold=>hold.id===g.hold)!;expect(a.particles[g.limb].x).toBe(h.x);expect(a.particles[g.limb].y).toBe(h.y);}});
 it('attaches an overlapping loose limb then releases that occupied hold after protection',()=>{const w=createWorld(),h=w.holds[0];w.grips=[];Object.assign(w.particles[BODY.handL],{x:h.x,y:h.y});expect(interactWithHold(w,h.id,100)).toBe('attached');expect(w.grips).toContainEqual({limb:BODY.handL,hold:h.id});expect(interactWithHold(w,h.id,450)).toBe('released');expect(w.grips).toEqual([]);});
 it('flicks the nearest loose limb and catches only its matching target',()=>{const w=createWorld(),h=generateDecisionRow(2).find(candidate=>candidate.profile==='SAFE')!;w.floorSupports=[];w.grips=[{limb:BODY.handL,hold:STARTING_HOLD_IDS.left}];expect(interactWithHold(w,h.id)).toBe('flicked');const target=w.launchTargets[0],limb=w.particles[target.limb];expect(Math.hypot(limb.x-limb.previous.x,limb.y-limb.previous.y)).toBeGreaterThan(0);expect(w.grips).toHaveLength(1);Object.assign(limb,{x:h.x,y:h.y});expect(tryGrip(w)).toBe(true);expect(w.grips).toContainEqual({limb:target.limb,hold:h.id});});
 it('rejects off-route attachment and treats it as a pass-through ghost',()=>{const w=createWorld(),h=w.holds[5],p=w.particles[BODY.handL];w.grips=[];w.links=[];Object.assign(p,{x:h.x+1,y:h.y,previous:{x:h.x+1,y:h.y-1}});expect(interactWithHold(w,h.id)).toBe('wrong-route');expect(w.grips).toHaveLength(0);stepWorld(w);expect(Math.hypot(p.x-h.x,p.y-h.y)).toBeLessThan(p.radius+h.radius);expect(w.feedback?.kind).toBe('wrong-route');});
 it('requires any support for torso launch and preserves existing momentum',()=>{const w=createWorld(),p=w.particles[BODY.head];p.previous.x=p.x-2;w.floorSupports=[];w.grips=[];expect(launchTorso(w,{x:50,y:0})).toBe(false);w.grips=[{limb:BODY.handL,hold:0}];const before=p.x-p.previous.x;expect(launchTorso(w,{x:50,y:0})).toBe(true);expect(w.grips).toHaveLength(0);expect(p.x-p.previous.x).toBeLessThan(before);expect(p.x-p.previous.x).not.toBeCloseTo(-TUNING.torsoLaunchBase*50*TUNING.fixedStep);});
 it('promotes PINK to BLUE exactly once per valid torso launch',()=>{const w=createWorld();expect(launchTorso(w,{x:0,y:0})).toBe(false);expect([w.activeRoute,w.nextRoute]).toEqual(['pink','blue']);expect(launchTorso(w,{x:50,y:0})).toBe(true);expect(w.activeRoute).toBe('blue');expect(w.nextRoute).toBe('green');const after=[w.activeRoute,w.nextRoute];expect(launchTorso(w,{x:50,y:0})).toBe(false);expect([w.activeRoute,w.nextRoute]).toEqual(after);});
 it('uses maximum four-support power on first launch and clears every support and transient once',()=>{const w=createWorld(),head=w.particles[BODY.head],before=head.x-head.previous.x,pull={x:50,y:0};w.launchTargets=[{limb:BODY.footL,hold:0,launchedAt:0,missed:false}];w.gripProtectedUntil[STARTING_HOLD_IDS.left]=999;expect(supportCount(w)).toBe(4);expect(launchTorso(w,pull)).toBe(true);expect(head.x-head.previous.x).toBeCloseTo(before-pull.x*torsoLaunchPower(4)*TUNING.fixedStep);expect(w).toMatchObject({grips:[],floorSupports:[],launchTargets:[],gripProtectedUntil:{},activeRoute:'blue',nextRoute:'green'});expect(launchTorso(w,pull)).toBe(false);expect([w.activeRoute,w.nextRoute]).toEqual(['blue','green']);});
 it('rejects an inactive color during flight',()=>{const w=createWorld();expect(launchTorso(w,{x:50,y:0})).toBe(true);expect(w.activeRoute).toBe('blue');expect(interactWithHold(w,STARTING_HOLD_IDS.left)).toBe('wrong-route');expect(w.grips).toHaveLength(0);});
 it('lets every particle pass through holds of every color',()=>{for(const color of ROUTE_SEQUENCE){const w=createWorld(),h=w.holds.find(candidate=>candidate.color===color)!;w.links=[];w.grips=[];w.floorSupports=[];for(const p of w.particles){p.x=h.x;p.y=h.y;p.previous={x:h.x,y:h.y};}stepWorld(w);for(const p of w.particles)expect(Math.hypot(p.x-h.x,p.y-h.y)).toBeLessThan(p.radius+h.radius);}});
 it('uses exact 5.2 torso power and stays strictly monotonic for one through four grips',()=>{expect(TUNING.torsoLaunchBase).toBe(5.2);const powers=[1,2,3,4].map(torsoLaunchPower);expect(powers[0]).toBe(5.2);expect(powers[1]).toBeGreaterThan(powers[0]);expect(powers[2]).toBeGreaterThan(powers[1]);expect(powers[3]).toBeGreaterThan(powers[2]);});
 it('combines floor and grip supports but clamps launch scaling to four',()=>{const w=createWorld();w.grips=[{limb:BODY.handL,hold:0},{limb:BODY.handR,hold:1},{limb:BODY.footL,hold:2}];expect(supportCount(w)).toBe(5);expect(torsoLaunchPower(supportCount(w))).toBe(torsoLaunchPower(4));});
 it('recovers a folded head outside the shoulders without instability',()=>{const w=createWorld(),head=w.particles[BODY.head];head.x=285;head.y=760;head.previous={x:284,y:759};for(let i=0;i<60;i++)stabilizeHead(w);const shoulderY=(w.particles[BODY.shoulderL].y+w.particles[BODY.shoulderR].y)/2;expect(head.y).toBeLessThan(shoulderY);for(const p of w.particles)expect([p.x,p.y,p.previous.x,p.previous.y].every(Number.isFinite)).toBe(true);expect(Math.hypot(head.x-head.previous.x,head.y-head.previous.y)).toBeLessThan(20);});
 it('protects only a newly attached hold for 350ms',()=>{const w=createWorld(),[first,other]=generateDecisionRow(2).slice(0,2);w.grips=[{limb:BODY.handR,hold:STARTING_HOLD_IDS.right}];Object.assign(w.particles[BODY.handL],{x:first.x,y:first.y});expect(interactWithHold(w,first.id,1000)).toBe('attached');expect(interactWithHold(w,first.id,1001)).toBe('protected');expect(w.feedback?.kind).toBe('protected');Object.assign(w.particles[BODY.footL],{x:other.x,y:other.y});expect(interactWithHold(w,other.id,1100)).toBe('attached');expect(w.grips).toContainEqual({limb:BODY.footL,hold:other.id});expect(interactWithHold(w,first.id,1349.999)).toBe('protected');expect(interactWithHold(w,first.id,1350)).toBe('released');});
 it('uses real input time rather than slow simulation time for protection expiry',()=>{const w=createWorld(),h=w.holds[0];w.grips=[];Object.assign(w.particles[BODY.handL],{x:h.x,y:h.y});expect(interactWithHold(w,h.id,500)).toBe('attached');for(let i=0;i<120;i++)stepWorld(w,TUNING.fixedStep*TUNING.slowMotionScale);expect(w.time).toBeCloseTo(TUNING.slowMotionScale);expect(interactWithHold(w,h.id,849)).toBe('protected');expect(interactWithHold(w,h.id,850)).toBe('released');});
 it('uses inclusive grade boundaries',()=>{expect(gradeApproach(TUNING.perfectApproach)).toBe('PERFECT');expect(gradeApproach(TUNING.goodApproach)).toBe('GOOD');expect(gradeApproach(TUNING.goodApproach-.001)).toBe('BARELY');});
});

describe('slow motion and endless course',()=>{
 it('starts the blue row zero strictly above the authored pair and keeps it conservatively reachable and visible with the floor',()=>{for(const runId of [1,2,17,99]){const w=createWorld(runId),starts=w.holds.filter(h=>h.id<1000),row0=generateDecisionRow(0,runId),safe=row0.find(h=>h.profile==='SAFE')!;expect(starts).toHaveLength(2);expect(row0.every(h=>h.color==='blue'&&h.row===0&&h.y<Math.min(...starts.map(s=>s.y)))).toBe(true);expect(safe.y).toBe(COURSE_ROW_ZERO_Y);for(const start of starts)expect(Math.hypot(safe.x-start.x,safe.y-start.y)).toBeLessThanOrEqual(TUNING.reachableDistance);const visible=[TUNING.groundY,...starts.map(h=>h.y),...row0.map(h=>h.y)].every(y=>y-w.renderCameraY>=0&&y-w.renderCameraY<=960);expect(visible).toBe(true);expect(w.particles.every(p=>p.y>=0&&p.y<=960)).toBe(true);}});
 it('places every non-start gameplay hold strictly above both start holds',()=>{for(const runId of [1,7,41]){const w=createWorld(runId),startY=Math.min(...w.holds.filter(h=>h.id<1000).map(h=>h.y));expect(w.holds.filter(h=>h.id>=1000).every(h=>h.y<startY)).toBe(true);}});
 it('drains focus only while airborne slow motion is held and recharges while supported',()=>{const w=createWorld();w.grips=[];w.floorSupports=[];expect(updateFocus(w,1,true)).toBe(TUNING.slowMotionScale);expect(w.focus).toBe(TUNING.focusCapacity-1);expect(updateFocus(w,1,false)).toBe(1);expect(w.focus).toBe(TUNING.focusCapacity-1);w.grips=[{limb:BODY.handL,hold:0}];expect(updateFocus(w,1,true)).toBe(1);expect(w.focus).toBeGreaterThan(TUNING.focusCapacity-1);w.focus=0;w.grips=[];expect(updateFocus(w,1,true)).toBe(1);});
 it('is stable per seed, distinct across seeds, and assigns exact row colors/profiles',()=>{for(const runId of [1,2,17,99]){expect(generateChunk(14,runId)).toEqual(generateChunk(14,runId));for(let row=0;row<80;row++){const holds=generateDecisionRow(row,runId);expect(new Set(holds.map(h=>h.profile))).toEqual(new Set(row%4===0?['SAFE','STANDARD','RISK','RECOVERY']:['SAFE','STANDARD','RISK']));expect(holds.every(h=>h.color===rowColor(row))).toBe(true);expect(rowColor(row)).toBe(ROUTE_SEQUENCE[(row+1)%3]);}}expect(generateChunk(14,1)).not.toEqual(generateChunk(14,2));});
 it('keeps generated holds bounded, uniquely identified, and usefully separated',()=>{for(const runId of [1,7,41,999]){const holds=Array.from({length:30},(_,chunk)=>generateChunk(chunk,runId)).flat(),ids=holds.map(h=>h.id);expect(new Set(ids).size).toBe(ids.length);for(const hold of holds){expect(hold.x-hold.radius).toBeGreaterThanOrEqual(TUNING.wallX);expect(hold.x+hold.radius).toBeLessThanOrEqual(TUNING.wallRight);}for(let i=0;i<holds.length;i++)for(let j=i+1;j<holds.length;j++){const distance=Math.hypot(holds[i].x-holds[j].x,holds[i].y-holds[j].y);expect(distance,`${runId}: ${holds[i].id}/${holds[i].profile} and ${holds[j].id}/${holds[j].profile}`).toBeGreaterThanOrEqual(TUNING.generatedHoldSeparation);}}});
 it('keeps authored and generated holds uniquely identified and non-overlapping',()=>{for(const runId of [1,7,41]){const authored=createWorld(runId).holds.filter(h=>h.id<1000),generated=Array.from({length:30},(_,chunk)=>generateChunk(chunk,runId)).flat(),all=[...authored,...generated];expect(new Set(all.map(h=>h.id)).size).toBe(all.length);for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)expect(Math.hypot(all[i].x-all[j].x,all[i].y-all[j].y),`${all[i].id}/${all[j].id}`).toBeGreaterThanOrEqual(all[i].radius+all[j].radius);}});
 it('guarantees the conservative SAFE chain across rows and chunk boundaries',()=>{for(const runId of [1,2,17,99,2026]){const safe=Array.from({length:400},(_,row)=>generateDecisionRow(row,runId).find(h=>h.profile==='SAFE')!);for(let i=1;i<safe.length;i++){expect(safe[i-1].y-safe[i].y).toBe(TUNING.safeRise);expect(Math.abs(safe[i].x-safe[i-1].x)).toBeLessThanOrEqual(TUNING.safeLateralDelta);expect(Math.hypot(safe[i].x-safe[i-1].x,safe[i].y-safe[i-1].y)).toBeLessThanOrEqual(TUNING.reachableDistance);}}});
 it('keeps progress monotonic and permanently prunes while protecting active targets',()=>{const w=createWorld(33),first=w.progressCameraY,held=w.holds[1];w.floorSupports=[];for(const p of w.particles){p.y-=700;p.previous.y=p.y+5;}updateCamera(w);expect(w.progressCameraY).toBeLessThan(first);const high=w.progressCameraY;for(const p of w.particles){p.y+=900;p.previous.y=p.y-5;}updateCamera(w);expect(w.progressCameraY).toBe(high);w.progressCameraY=-2000;w.grips=[{limb:BODY.handR,hold:held.id}];maintainCourse(w);expect(w.holds).toContainEqual(held);const highest=w.highestChunk,watermark=w.pruneCutoffY;w.grips=[];maintainCourse(w);expect(w.holds).not.toContainEqual(held);w.renderCameraY=500;maintainCourse(w);expect(w.highestChunk).toBe(highest);expect(w.pruneCutoffY).toBe(watermark);expect(w.holds.some(h=>h.id===held.id)).toBe(false);});
});
