import './style.css';
import { BODY, launchTorso, stepWorld, supportCount, torsoCenter, tryGrip, updateFocus } from './physics/world';
import { TUNING } from './physics/tuning';
import type { Vec2 } from './physics/types';
import { previewEndpoint, pullGauge } from './physics/slingshot';
import { beginDrag, dragPull, finalizeDrag, updateDrag, type DragState } from './drag';
import { canControl, createRun, registerCatch, registerGripRelease, registerLaunch, restartRun, updateRun } from './run';
import { bestHeightStorage } from './storage';
import { beginHoldPress, clearHoldPress, updateHoldPress, type HoldPress } from './holdPress';
import { LOGICAL_HEIGHT,LOGICAL_WIDTH,logicalToWorld,screenToLogical,viewportTransform,type ViewportTransform } from './viewport';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!,context=canvas.getContext('2d')!,bestStore=bestHeightStorage(safeStorage());
let run=createRun(1,bestStore.read()),view:ViewportTransform=viewportTransform(innerWidth,innerHeight),accumulator=0,previousTime=performance.now(),hoveredHold=-1,drag:DragState|undefined,holdPress:HoldPress|null=null,spaceHeld=false;
function safeStorage():Storage|null{try{return localStorage}catch{return null}}
function resize(){const ratio=Math.min(devicePixelRatio,2);canvas.width=Math.round(innerWidth*ratio);canvas.height=Math.round(innerHeight*ratio);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;view=viewportTransform(innerWidth,innerHeight);}
function point(e:PointerEvent):Vec2|null{const p=screenToLogical({x:e.clientX,y:e.clientY},view);return p.x<0||p.x>LOGICAL_WIDTH||p.y<0||p.y>LOGICAL_HEIGHT?null:logicalToWorld(p,run.world.renderCameraY);}
function line(a:Vec2,b:Vec2,width:number,color:string){context.beginPath();context.moveTo(a.x,a.y);context.lineTo(b.x,b.y);context.lineWidth=width;context.strokeStyle=color;context.lineCap='round';context.stroke();}
function holdAt(p:Vec2){return run.world.holds.map(h=>({id:h.id,d:Math.hypot(p.x-h.x,p.y-h.y)})).filter(v=>v.d<=22).sort((a,b)=>a.d-b.d||a.id-b.id)[0]?.id??-1;}
function torsoAt(p:Vec2){const c=torsoCenter(run.world);return Math.abs(p.x-c.x)<48&&Math.abs(p.y-c.y)<65;}
function reset(){if(run.phase==='RESULT')bestStore.write(run.bestHeight);run=restartRun(run);accumulator=0;hoveredHold=-1;drag=undefined;holdPress=null;spaceHeld=false;}
function finishHoldPress(e?:PointerEvent){holdPress=clearHoldPress(holdPress,e?.pointerId);}
function finishDrag(e?:PointerEvent){if(!drag)return;if(e&&e.pointerId!==drag.pointerId)return;const p=e&&point(e);if(p)updateDrag(drag,p);const active=drag;drag=undefined;if(finalizeDrag(active,pull=>launchTorso(run.world,pull)))registerLaunch(run);}
function render(){
 const ratio=Math.min(devicePixelRatio,2),w=run.world;context.setTransform(ratio,0,0,ratio,0,0);context.fillStyle='#070b14';context.fillRect(0,0,innerWidth,innerHeight);context.save();context.translate(view.offsetX,view.offsetY);context.scale(view.scale,view.scale);context.beginPath();context.rect(0,0,LOGICAL_WIDTH,LOGICAL_HEIGHT);context.clip();context.fillStyle='#111827';context.fillRect(0,0,LOGICAL_WIDTH,LOGICAL_HEIGHT);context.save();context.translate(0,-w.renderCameraY);context.fillStyle='#273244';context.fillRect(100,w.renderCameraY,520,LOGICAL_HEIGHT);context.strokeStyle='rgba(148,163,184,.12)';context.fillStyle='rgba(203,213,225,.38)';context.lineWidth=2;context.font='11px system-ui';const firstBand=Math.floor(w.renderCameraY/110)*110;for(let y=firstBand;y<=w.renderCameraY+LOGICAL_HEIGHT;y+=110){context.beginPath();context.moveTo(100,y);context.lineTo(122,y);context.moveTo(598,y);context.lineTo(620,y);context.stroke();if(y<=0)context.fillText(`${Math.round(-y)}m`,128,y+4);}context.fillStyle='#64748b';context.fillRect(80,TUNING.groundY,560,50);context.fillStyle='#94a3b8';context.fillRect(80,TUNING.groundY,560,8);
 const colors={pink:'#e879f9',blue:'#60a5fa',green:'#34d399'};for(const h of w.holds){const active=h.color===w.activeRoute,next=h.color===w.nextRoute,selected=w.grips.some(g=>g.hold===h.id),pressed=holdPress?.holdId===h.id;context.beginPath();context.arc(h.x,h.y,h.radius,0,Math.PI*2);context.fillStyle=selected?'#fbbf24':colors[h.color];context.globalAlpha=active?1:next&&w.grips.length?.62:.28;context.fill();context.globalAlpha=1;context.strokeStyle=hoveredHold===h.id?'#fff':active?'#fff':next&&w.grips.length?'#fef08a':'#64748b';context.lineWidth=hoveredHold===h.id?5:3;context.stroke();if(pressed){context.beginPath();context.arc(h.x,h.y,h.radius+8,0,Math.PI*2);context.strokeStyle='rgba(253,230,138,.8)';context.lineWidth=3;context.stroke();}}
 for(const l of w.links)line(w.particles[l.a],w.particles[l.b],9,'#cbd5e1');for(const [i,p] of w.particles.entries()){context.beginPath();context.arc(p.x,p.y,p.radius,0,Math.PI*2);context.fillStyle=i===BODY.head?'#f1f5f9':w.grips.some(g=>g.limb===i)?'#fbbf24':'#64748b';context.fill();}if(drag){const c=torsoCenter(w),pull=dragPull(drag),gauge=pullGauge(pull),preview=previewEndpoint(c,pull);context.beginPath();context.arc(c.x,c.y,TUNING.maximumTorsoDrag,0,Math.PI*2);context.strokeStyle=gauge.ratio>=1?'#fbbf24':'rgba(251,191,36,.35)';context.lineWidth=3;context.setLineDash([10,8]);context.stroke();context.setLineDash([]);line(c,preview,6,'#fbbf24');const angle=Math.atan2(preview.y-c.y,preview.x-c.x);line(preview,{x:preview.x-18*Math.cos(angle-.55),y:preview.y-18*Math.sin(angle-.55)},6,'#fbbf24');line(preview,{x:preview.x-18*Math.cos(angle+.55),y:preview.y-18*Math.sin(angle+.55)},6,'#fbbf24');context.fillStyle=gauge.ratio>=1?'#fef08a':'#f8fafc';context.font='800 18px system-ui';context.fillText(gauge.ratio>=1?'MAX':`${Math.round(gauge.ratio*100)}%`,preview.x+12,preview.y-12);}context.restore();
 context.fillStyle='rgba(7,11,20,.9)';context.fillRect(20,18,680,112);context.fillStyle='#f8fafc';context.font='700 17px system-ui';context.fillText(`${run.phase}  |  HEIGHT ${Math.floor(w.height)}  |  LAUNCHES ${run.launches}  |  CATCHES ${run.catches}`,38,46);context.font='700 13px system-ui';context.fillStyle='#cbd5e1';context.fillText('CURRENT',38,75);context.fillStyle=colors[w.activeRoute];context.fillRect(108,59,86,23);context.fillStyle='#07111d';context.fillText(w.activeRoute.toUpperCase(),122,76);context.fillStyle='#cbd5e1';context.fillText('NEXT',220,75);context.fillStyle=colors[w.nextRoute];context.fillRect(265,59,86,23);context.fillStyle='#07111d';context.fillText(w.nextRoute.toUpperCase(),278,76);context.font='13px system-ui';context.fillStyle='#cbd5e1';context.fillText('FLICK HOLDS  |  DRAG TORSO  |  SPACE: AIR SLOW-MO',38,108);context.fillStyle='#334155';context.fillRect(500,99,170,8);context.fillStyle='#fbbf24';context.fillRect(500,99,170*w.focus/TUNING.focusCapacity,8);
 if(run.phase==='RESULT'){context.fillStyle='rgba(3,7,18,.88)';context.fillRect(110,270,500,400);context.textAlign='center';context.fillStyle='#f8fafc';context.font='900 46px system-ui';context.fillText('RUN COMPLETE',360,345);context.font='700 19px system-ui';context.fillStyle='#fb7185';context.fillText(run.deathCause==='GROUND_IMPACT'?'GROUND IMPACT':'LOST BELOW ROUTE',360,385);context.fillStyle='#f8fafc';context.font='700 25px system-ui';context.fillText(`HEIGHT  ${Math.floor(w.height)}`,360,430);context.fillText(`BEST  ${Math.floor(run.bestHeight)}`,360,475);context.fillText(`LAUNCHES  ${run.launches}`,360,520);context.fillText(`CATCHES  ${run.catches}`,360,565);context.font='600 18px system-ui';context.fillStyle='#fbbf24';context.fillText('CLICK OR PRESS ENTER TO CLIMB AGAIN',360,620);context.textAlign='start';}else if(run.phase==='FALLING'){context.textAlign='center';context.fillStyle='#fb7185';context.font='900 34px system-ui';context.fillText('FALLING — R TO RESTART',360,160);context.textAlign='start';}context.restore();
}
canvas.addEventListener('pointermove',e=>{const p=point(e);hoveredHold=p&&canControl(run)?holdAt(p):-1;if(drag&&e.pointerId===drag.pointerId&&p)updateDrag(drag,p);});canvas.addEventListener('pointerleave',()=>hoveredHold=-1);canvas.addEventListener('pointerdown',e=>{if(run.phase==='RESULT'){reset();return;}if(!canControl(run)||drag||holdPress)return;const p=point(e);if(!p)return;const hold=holdAt(p);if(hold>=0){const started=beginHoldPress(run.world,hold,e.pointerId,performance.now());holdPress=started.press;if(holdPress)canvas.setPointerCapture(e.pointerId);if(started.interaction==='released')registerGripRelease(run);else if(started.interaction==='attached')registerCatch(run);return;}if(torsoAt(p)&&supportCount(run.world)>0){drag=beginDrag(p,e.pointerId);canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointerup',e=>{finishHoldPress(e);finishDrag(e);});canvas.addEventListener('pointercancel',e=>{finishHoldPress(e);finishDrag(e);});canvas.addEventListener('lostpointercapture',e=>{finishHoldPress(e);finishDrag(e);});addEventListener('pointerup',e=>{finishHoldPress(e);finishDrag(e);});
function frame(now:number){const elapsed=Math.min((now-previousTime)/1000,TUNING.maxFrameTime);previousTime=now;const timeScale=canControl(run)?updateFocus(run.world,elapsed,spaceHeld):1;accumulator+=elapsed*timeScale;while(accumulator>=TUNING.fixedStep&&run.phase!=='RESULT'){stepWorld(run.world);let caught=false;if(canControl(run)&&holdPress)caught=updateHoldPress(run.world,holdPress,now);if(canControl(run)&&tryGrip(run.world,now))caught=true;if(caught)registerCatch(run);accumulator-=TUNING.fixedStep;}const prior=run.phase;updateRun(run,elapsed);if(canControl(run)===false)holdPress=null;if(prior!=='RESULT'&&run.phase==='RESULT')bestStore.write(run.bestHeight);render();requestAnimationFrame(frame);}
addEventListener('keydown',e=>{if(e.code==='Enter'&&run.phase==='RESULT')reset();else if(e.code==='KeyR'&&run.phase==='FALLING')reset();else if(e.code==='Space'&&canControl(run)){spaceHeld=true;e.preventDefault();}});addEventListener('keyup',e=>{if(e.code==='Space')spaceHeld=false;});addEventListener('blur',()=>{spaceHeld=false;finishHoldPress();finishDrag();});addEventListener('resize',resize);resize();requestAnimationFrame(frame);
