import './style.css';
import {BODY,launchTorso,stepWorld,supportCount,torsoCenter,tryGrip,updateFocus} from './physics/world';
import {TUNING} from './physics/tuning';
import type {Vec2} from './physics/types';
import {previewEndpoint,pullGauge} from './physics/slingshot';
import {beginDrag,dragPull,finalizeDrag,updateDrag,type DragState} from './drag';
import {canControl,createRun,registerCatch,registerGripRelease,registerLaunch,restartRun,updateRun} from './run';
import {bestHeightStorage} from './storage';
import {beginHoldPress,clearHoldPress,updateHoldPress,type HoldPress} from './holdPress';
import {LOGICAL_HEIGHT,LOGICAL_WIDTH,logicalToWorld,screenToLogical,viewportTransform,type ViewportTransform} from './viewport';
import {drawClimber,drawGym,drawHold} from './render/canvas';
import {ROUTE_COLORS} from './render/design';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!,context=canvas.getContext('2d')!,bestStore=bestHeightStorage(safeStorage());
let run=createRun(1,bestStore.read()),view:ViewportTransform=viewportTransform(innerWidth,innerHeight),accumulator=0,previousTime=performance.now(),hoveredHold=-1,drag:DragState|undefined,holdPress:HoldPress|null=null,spaceHeld=false;
function safeStorage():Storage|null{try{return localStorage}catch{return null}}
function resize(){const ratio=Math.min(devicePixelRatio,2);canvas.width=Math.round(innerWidth*ratio);canvas.height=Math.round(innerHeight*ratio);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;view=viewportTransform(innerWidth,innerHeight);}
function point(e:PointerEvent):Vec2|null{const p=screenToLogical({x:e.clientX,y:e.clientY},view);return p.x<0||p.x>LOGICAL_WIDTH||p.y<0||p.y>LOGICAL_HEIGHT?null:logicalToWorld(p,run.world.renderCameraY);}
function line(a:Vec2,b:Vec2,width:number,color:string){context.beginPath();context.moveTo(a.x,a.y);context.lineTo(b.x,b.y);context.lineWidth=width;context.strokeStyle=color;context.lineCap='round';context.stroke();}
function holdAt(p:Vec2){return run.world.holds.map(h=>({id:h.id,d:Math.hypot(p.x-h.x,p.y-h.y)})).filter(v=>v.d<=22).sort((a,b)=>a.d-b.d||a.id-b.id)[0]?.id??-1;}
function torsoAt(p:Vec2){const c=torsoCenter(run.world);return Math.abs(p.x-c.x)<48&&Math.abs(p.y-c.y)<65;}
function reset(){if(run.phase==='RESULT')bestStore.write(run.bestHeight);run=restartRun(run);accumulator=0;hoveredHold=-1;drag=undefined;holdPress=null;spaceHeld=false;}
function finishHoldPress(e?:PointerEvent){holdPress=clearHoldPress(holdPress,e?.pointerId);}
function finishDrag(e?:PointerEvent){if(!drag)return;if(e&&e.pointerId!==drag.pointerId)return;const p=e&&point(e);if(p)updateDrag(drag,p);const active=drag;drag=undefined;if(finalizeDrag(active,pull=>launchTorso(run.world,pull)))registerLaunch(run);}
function panel(x:number,y:number,width:number,height:number,radius=18){context.beginPath();context.roundRect(x,y,width,height,radius);context.fillStyle='rgba(12,19,27,.9)';context.fill();context.strokeStyle='rgba(255,255,255,.12)';context.lineWidth=1.5;context.stroke();}
function pill(x:number,y:number,label:string,value:string,color:string,width:number){context.fillStyle='rgba(255,255,255,.07)';context.beginPath();context.roundRect(x,y,width,38,12);context.fill();context.fillStyle='#96a9b8';context.font='700 10px system-ui';context.fillText(label,x+12,y+14);context.fillStyle=color;context.font='900 15px system-ui';context.fillText(value,x+12,y+31);}
function routeLabel(route:keyof typeof ROUTE_COLORS){return route==='pink'?'분홍':route==='blue'?'파랑':'초록';}

function render(){
  const ratio=Math.min(devicePixelRatio,2),w=run.world;context.setTransform(ratio,0,0,ratio,0,0);context.fillStyle='#080d13';context.fillRect(0,0,innerWidth,innerHeight);context.save();context.translate(view.offsetX,view.offsetY);context.scale(view.scale,view.scale);context.beginPath();context.rect(0,0,LOGICAL_WIDTH,LOGICAL_HEIGHT);context.clip();
  context.save();context.translate(0,-w.renderCameraY);drawGym(context,w.renderCameraY);
  context.fillStyle='rgba(35,43,48,.62)';context.font='800 11px system-ui';const firstBand=Math.floor(w.renderCameraY/110)*110;for(let y=firstBand;y<=w.renderCameraY+LOGICAL_HEIGHT;y+=110){if(y<=0)context.fillText(`${Math.round(-y)}m`,105,y+4);}
  for(const h of w.holds)drawHold(context,h,{active:h.color===w.activeRoute,next:h.color===w.nextRoute,gripped:w.grips.some(g=>g.hold===h.id),hovered:hoveredHold===h.id,pressed:holdPress?.holdId===h.id});
  drawClimber(context,w);
  if(drag){const c=torsoCenter(w),pull=dragPull(drag),gauge=pullGauge(pull),preview=previewEndpoint(c,pull);context.beginPath();context.arc(c.x,c.y,TUNING.maximumTorsoDrag,0,Math.PI*2);context.strokeStyle=gauge.ratio>=1?'rgba(255,218,75,.9)':'rgba(255,255,255,.25)';context.lineWidth=gauge.ratio>=1?5:2;context.setLineDash([10,8]);context.stroke();context.setLineDash([]);context.shadowColor='#ffcf3f';context.shadowBlur=gauge.ratio>=1?20:8;line(c,preview,gauge.ratio>=1?9:6,gauge.ratio>=1?'#ffe15c':'#fff1a8');context.shadowBlur=0;const angle=Math.atan2(preview.y-c.y,preview.x-c.x);line(preview,{x:preview.x-18*Math.cos(angle-.55),y:preview.y-18*Math.sin(angle-.55)},7,'#ffe15c');line(preview,{x:preview.x-18*Math.cos(angle+.55),y:preview.y-18*Math.sin(angle+.55)},7,'#ffe15c');context.fillStyle='#101820';context.beginPath();context.roundRect(preview.x+10,preview.y-31,58,26,10);context.fill();context.fillStyle=gauge.ratio>=1?'#ffe15c':'#fff';context.font='900 14px system-ui';context.fillText(gauge.ratio>=1?'최대!':`${Math.round(gauge.ratio*100)}%`,preview.x+21,preview.y-13);}
  context.restore();
  const supports=supportCount(w),catching=supports===0,targetRoute=catching?w.activeRoute:w.nextRoute,target=ROUTE_COLORS[targetRoute];panel(18,16,684,140,20);context.fillStyle='#f4f7f8';context.font='950 18px system-ui';context.fillText('최상의 클라이머',34,43);context.fillStyle='#8fa3b2';context.font='700 10px system-ui';context.fillText(catching?'비행 중':'지지하고 · 당기고 · 날아가기',34,61);
  context.fillStyle='rgba(255,255,255,.07)';context.beginPath();context.roundRect(246,27,228,55,16);context.fill();context.strokeStyle=target.light;context.lineWidth=2;context.stroke();context.textAlign='center';context.fillStyle='#aebec9';context.font='800 10px system-ui';context.fillText(catching?'지금 잡을 색':'다음 목표 색',360,45);context.fillStyle=target.light;context.font='950 23px system-ui';context.fillText(routeLabel(targetRoute),360,70);context.textAlign='start';
  pill(34,99,'높이',`${Math.floor(w.height)} m`,'#ffffff',102);pill(144,99,'지지점',`${supports}/4`,'#ffe15c',96);pill(248,99,'최고',`${Math.floor(run.bestHeight)} m`,'#ffffff',96);
  context.fillStyle=spaceHeld&&catching?'rgba(98,217,255,.25)':'rgba(255,255,255,.07)';context.beginPath();context.roundRect(352,99,330,38,12);context.fill();context.strokeStyle=spaceHeld&&catching?'#82e4ff':'rgba(255,255,255,.12)';context.lineWidth=1.5;context.stroke();context.fillStyle='#eefaff';context.beginPath();context.roundRect(364,106,76,24,7);context.fill();context.fillStyle='#152431';context.font='950 11px system-ui';context.fillText('스페이스',378,122);context.fillStyle='#c8d7df';context.font='800 11px system-ui';context.fillText('비행 중 길게 눌러 느리게',450,117);context.fillStyle='rgba(255,255,255,.15)';context.beginPath();context.roundRect(450,123,214,6,3);context.fill();context.fillStyle=w.focus<1?'#ff6b6b':'#62d9ff';context.beginPath();context.roundRect(450,123,214*w.focus/TUNING.focusCapacity,6,3);context.fill();
  if(spaceHeld&&canControl(run)&&catching){context.fillStyle='rgba(49,174,230,.12)';context.fillRect(0,0,720,960);context.strokeStyle='rgba(110,220,255,.8)';context.lineWidth=7;context.strokeRect(4,4,712,952);context.textAlign='center';context.fillStyle='#a8ecff';context.font='900 17px system-ui';context.fillText('집중 모드 · 스페이스',360,184);context.textAlign='start';}
  if(run.phase==='READY'){panel(148,772,424,120,18);context.textAlign='center';context.fillStyle='#fff';context.font='900 20px system-ui';context.fillText('몸통을 누르고 당기세요',360,808);context.fillStyle='#b8c7d1';context.font='600 13px system-ui';context.fillText('놓으면 몸 전체가 발사됩니다',360,834);context.fillText('같은 색 홀드를 클릭하거나 꾹 눌러 잡으세요',360,858);context.fillStyle='#ffe15c';context.font='800 12px system-ui';context.fillText('비행 중 스페이스 = 느리게 보기',360,880);context.textAlign='start';}
  if(run.phase==='FALLING'){context.textAlign='center';context.fillStyle='rgba(11,15,22,.72)';context.fillRect(0,0,720,960);context.fillStyle='#ff6c78';context.font='950 42px system-ui';context.fillText('추락 중',360,210);context.fillStyle='#fff';context.font='700 15px system-ui';context.fillText('잡을 수 있는 홀드가 없습니다',360,239);context.textAlign='start';}
  if(run.phase==='RESULT'){context.fillStyle='rgba(5,9,14,.74)';context.fillRect(0,0,720,960);panel(104,230,512,470,28);context.textAlign='center';context.fillStyle='#ff707b';context.font='950 15px system-ui';context.fillText(run.deathCause==='GROUND_IMPACT'?'매트에 충돌했습니다':'루트 아래로 떨어졌습니다',360,282);context.fillStyle='#fff';context.font='950 42px system-ui';context.fillText('등반 종료',360,334);context.fillStyle='#ffe15c';context.font='950 64px system-ui';context.fillText(`${Math.floor(w.height)}m`,360,417);context.fillStyle='#91a4b3';context.font='700 13px system-ui';context.fillText('최종 높이',360,443);context.fillStyle='#eef4f7';context.font='800 18px system-ui';context.fillText(`최고 기록  ${Math.floor(run.bestHeight)}m`,360,493);context.fillText(`발사  ${run.launches}회     잡기  ${run.catches}회`,360,532);context.fillStyle='#f6c94c';context.beginPath();context.roundRect(170,580,380,66,18);context.fill();context.fillStyle='#18212a';context.font='950 17px system-ui';context.fillText('클릭 또는 엔터로 다시 등반하기',360,621);context.textAlign='start';}
  context.restore();
}

canvas.addEventListener('pointermove',e=>{const p=point(e);hoveredHold=p&&canControl(run)?holdAt(p):-1;if(drag&&e.pointerId===drag.pointerId&&p)updateDrag(drag,p);});canvas.addEventListener('pointerleave',()=>hoveredHold=-1);canvas.addEventListener('pointerdown',e=>{if(run.phase==='RESULT'){reset();return;}if(!canControl(run)||drag||holdPress)return;const p=point(e);if(!p)return;const hold=holdAt(p);if(hold>=0){const started=beginHoldPress(run.world,hold,e.pointerId,performance.now());holdPress=started.press;if(holdPress)canvas.setPointerCapture(e.pointerId);if(started.interaction==='released')registerGripRelease(run);else if(started.interaction==='attached')registerCatch(run);return;}if(torsoAt(p)&&supportCount(run.world)>0){drag=beginDrag(p,e.pointerId);canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointerup',e=>{finishHoldPress(e);finishDrag(e);});canvas.addEventListener('pointercancel',e=>{finishHoldPress(e);finishDrag(e);});canvas.addEventListener('lostpointercapture',e=>{finishHoldPress(e);finishDrag(e);});addEventListener('pointerup',e=>{finishHoldPress(e);finishDrag(e);});
function frame(now:number){const elapsed=Math.min((now-previousTime)/1000,TUNING.maxFrameTime);previousTime=now;const timeScale=canControl(run)?updateFocus(run.world,elapsed,spaceHeld):1;accumulator+=elapsed*timeScale;while(accumulator>=TUNING.fixedStep&&run.phase!=='RESULT'){stepWorld(run.world);let caught=false;if(canControl(run)&&holdPress)caught=updateHoldPress(run.world,holdPress,now);if(canControl(run)&&tryGrip(run.world,now))caught=true;if(caught)registerCatch(run);accumulator-=TUNING.fixedStep;}const prior=run.phase;updateRun(run,elapsed);if(canControl(run)===false)holdPress=null;if(prior!=='RESULT'&&run.phase==='RESULT')bestStore.write(run.bestHeight);render();requestAnimationFrame(frame);}
addEventListener('keydown',e=>{if(e.code==='Enter'&&run.phase==='RESULT')reset();else if(e.code==='KeyR'&&run.phase==='FALLING')reset();else if(e.code==='Space'&&canControl(run)){spaceHeld=true;e.preventDefault();}});addEventListener('keyup',e=>{if(e.code==='Space')spaceHeld=false;});addEventListener('blur',()=>{spaceHeld=false;finishHoldPress();finishDrag();});addEventListener('resize',resize);resize();requestAnimationFrame(frame);
