import {describe,expect,it} from 'vitest';
import type {Hold} from './physics/types';
import {BODY,STARTING_HOLD_IDS,launchTorso,supportCount,torsoCenter} from './physics/world';
import {TUNING} from './physics/tuning';
import {IRRECOVERABLE_APEX_DROP,RECOVERY_CAMERA_DROP,RESULT_DROP_AFTER_IMPACT,createRun,dynamicDeathBoundary,hasViableRecoveryHold,registerCatch,registerGripRelease,registerLaunch,restartRun,updateRun,viableRecoveryHolds} from './run';

function loseSupports(run:ReturnType<typeof createRun>){expect(launchTorso(run.world,{x:0,y:150})).toBe(true);registerLaunch(run);}
function setTorso(run:ReturnType<typeof createRun>,x:number,y:number){for(const id of [BODY.shoulderL,BODY.shoulderR,BODY.hipL,BODY.hipR]){const p=run.world.particles[id];p.x=x;p.y=y;p.previous.x=x;p.previous.y=y-1;}}
function moveTorso(run:ReturnType<typeof createRun>,dy:number,dt=.04){const torso=torsoCenter(run.world);setTorso(run,torso.x,torso.y+dy);updateRun(run,dt);}
function recoveryHold(run:ReturnType<typeof createRun>,dx=0,dy=100,overrides:Partial<Hold>={}):Hold{const torso=torsoCenter(run.world);return{id:99001,x:torso.x+dx,y:torso.y+dy,radius:TUNING.holdRadius,color:run.world.activeRoute,...overrides};}

describe('T9.4 spatial run state machine',()=>{
 it('stays ready with support and records one real launch',()=>{const run=createRun();expect(run.phase).toBe('READY');expect(supportCount(run.world)).toBe(4);updateRun(run,1000);expect(run.phase).toBe('READY');loseSupports(run);expect(run).toMatchObject({phase:'AIRBORNE',launches:1,impactY:null,deathCause:null});});
 it('long airborne duration and radically different dt never decide the phase',()=>{const a=createRun(),b=createRun();loseSupports(a);loseSupports(b);a.world.holds.push(recoveryHold(a));b.world.holds.push(recoveryHold(b));for(const run of [a,b]){moveTorso(run,-100,run===a?.001:20);moveTorso(run,RECOVERY_CAMERA_DROP+10,run===a?40:.001);updateRun(run,10000);}expect(a.phase).toBe('AIRBORNE');expect(b.phase).toBe('AIRBORNE');expect(a.flightApexY).toBe(b.flightApexY);});
 it('follows with the render camera after a recoverable drop without moving progress',()=>{const run=createRun();loseSupports(run);moveTorso(run,-200);run.world.holds.push(recoveryHold(run,0,100));const progress=run.world.progressCameraY,before=run.world.renderCameraY;moveTorso(run,RECOVERY_CAMERA_DROP+1,99);expect(run.phase).toBe('AIRBORNE');expect(run.world.renderCameraY).toBeGreaterThan(before);expect(run.world.progressCameraY).toBe(progress);});
 it('counts only existing, unoccupied active-route holds inside the bounded corridor',()=>{const run=createRun();loseSupports(run);const valid=recoveryHold(run);run.world.holds=[valid];expect(viableRecoveryHolds(run.world)).toEqual([valid]);for(const invalid of [recoveryHold(run,0,100,{color:run.world.nextRoute}),recoveryHold(run,0,-81),recoveryHold(run,0,433),recoveryHold(run,286,100)]){run.world.holds=[invalid];expect(hasViableRecoveryHold(run.world)).toBe(false);}run.world.holds=[];expect(hasViableRecoveryHold(run.world)).toBe(false);run.world.holds=[valid];run.world.grips=[{limb:BODY.handL,hold:valid.id}];expect(hasViableRecoveryHold(run.world)).toBe(false);});
 it('stays airborne beyond 528px with a viable hold, then falls when it is removed',()=>{const run=createRun();loseSupports(run);moveTorso(run,-600);run.world.holds.push(recoveryHold(run,0,IRRECOVERABLE_APEX_DROP+100));moveTorso(run,IRRECOVERABLE_APEX_DROP+1,.001);expect(run.phase).toBe('AIRBORNE');run.world.holds=run.world.holds.filter(h=>h.id!==99001);moveTorso(run,1,100);expect(run.phase).toBe('FALLING');});
 it.each([0,-1800])('crossing dynamic boundary forces falling at progress %s',progress=>{const run=createRun();loseSupports(run);run.world.progressCameraY=progress;const boundary=dynamicDeathBoundary(progress);setTorso(run,300,boundary.y-1);run.previousTorsoY=boundary.y-1;setTorso(run,300,boundary.y+1);updateRun(run,0);expect(run.phase).toBe('FALLING');expect(run.impactY).toBe(boundary.y+1);expect(run.deathCause).toBe(boundary.cause);});
 it('reaches result after 180px of world drop, never from time alone',()=>{const run=createRun();loseSupports(run);const boundary=dynamicDeathBoundary(0);setTorso(run,300,boundary.y+1);updateRun(run,50);expect(run.phase).toBe('FALLING');const impact=run.impactY!;updateRun(run,100000);expect(run.phase).toBe('FALLING');setTorso(run,300,impact+RESULT_DROP_AFTER_IMPACT-1);updateRun(run,0);expect(run.phase).toBe('FALLING');setTorso(run,300,impact+RESULT_DROP_AFTER_IMPACT);updateRun(run,0);expect(run.phase).toBe('RESULT');});
 it('catch resets spatial flight state and final release starts a fresh flight',()=>{const run=createRun();loseSupports(run);moveTorso(run,20);run.world.grips=[{limb:BODY.handL,hold:run.world.holds[0].id}];registerCatch(run);expect(run).toMatchObject({phase:'GRIPPING',flightApexY:null,previousTorsoY:null,impactY:null,catches:1,launches:1});run.world.grips=[];registerGripRelease(run);expect(run.phase).toBe('AIRBORNE');expect(run.flightApexY).toBe(torsoCenter(run.world).y);expect(run.launches).toBe(1);});
 it('restart restores exact supports, cameras, spatial state, stats and deterministic world',()=>{const run=createRun(4,12);run.launches=3;run.catches=2;run.world.height=30;run.world.progressCameraY=-2000;run.world.renderCameraY=400;run.world.pruneCutoffY=-500;run.impactY=900;run.deathCause='GROUND_IMPACT';run.bestHeight=30;const next=restartRun(run);expect(next).toMatchObject({identity:5,phase:'READY',launches:0,catches:0,bestHeight:30,flightApexY:null,previousTorsoY:null,impactY:null,deathCause:null});expect(next.world).toMatchObject({runId:5,progressCameraY:0,renderCameraY:0,pruneCutoffY:null,floorSupports:[BODY.footL,BODY.footR],grips:[{limb:BODY.handL,hold:STARTING_HOLD_IDS.left},{limb:BODY.handR,hold:STARTING_HOLD_IDS.right}]});expect(next.world).toEqual(createRun(5).world);});
});
